### ISSUE TITLE
FirebaseMessaging.onBackgroundMessage() .createNotificationChannel, FirebaseMessaging.instance(Not able to declare these all.)

### ISSUE THREAD

**Issue by MuhammadSufyanMalik** [karankharode/Flutter-2.0-Firebase-Push-Notifications#1]
I am getting these errors while following your code.

![image](https://user-images.githubusercontent.com/44575277/121846205-53327d80-ccef-11eb-8bd3-7f7e0f77e1ff.png)

**Comment by karankharode** [comment]
This is an Invalid Issue...No such error occurs with the same Dependency version and the same implementation.
Please share the details of your code and implementation to search for any error with implementation.
I am closing this issue for the same.
Thanks and please contact for more assistance.

**Comment by MuhammadSufyanMalik** [comment]
> This is an Invalid Issue...No such error occurs with the same Dependency version and the same implementation.
> Please share the details of your code and implementation to search for any error with implementation.
> I am closing this issue for the same.
> Thanks and please contact for more assistance.

I came to know my issue it was my firebase version issue.
Thanks 
we will be waiting for IOS notification. :)

**Comment by MuhammadSufyanMalik** [comment]
now after updating on this flutter messaging version, I am getting the below error while running the app. can you help?
Thanks

![image](https://user-images.githubusercontent.com/44575277/122066970-db9e4480-cdfb-11eb-8357-346c1c163cbd.png)

**Comment by divyadave1205** [comment]
[Skip to content](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#start-of-content)[](https://github.com/)
Search or jump to…
[Pull requests](https://github.com/pulls)
[Issues](https://github.com/issues)
[Marketplace](https://github.com/marketplace)
[Explore](https://github.com/explore)[](https://github.com/notifications)
 
@divyadave1205 
[karankharode](https://github.com/karankharode)
/
[Flutter-2.0-Firebase-Push-Notifications](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications)
Public
[Code](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications)
Issues
2
[Pull requests](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/pulls)
[Actions](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/actions)
[Projects](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/projects?type=beta)
[Wiki](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/wiki)
[Security](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/security)
[Insights](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/pulse)
FirebaseMessaging.onBackgroundMessage() .createNotificationChannel, FirebaseMessaging.instance(Not able to declare these all.) #1
 Closed
[MuhammadSufyanMalik](https://github.com/MuhammadSufyanMalik) opened this issue on 14 Jun 2021 · 2 comments
 Closed
[FirebaseMessaging.onBackgroundMessage() .createNotificationChannel, FirebaseMessaging.instance(Not able to declare these all.)](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#)
#1
[MuhammadSufyanMalik](https://github.com/MuhammadSufyanMalik)[](https://github.com/MuhammadSufyanMalik) opened this issue on 14 Jun 2021 · 2 comments
Comments
@[MuhammadSufyanMalik](https://github.com/MuhammadSufyanMalik)
MuhammadSufyanMalik commented [on 14 Jun 2021](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#issue-920035668)[](https://user-images.githubusercontent.com/44575277/121846205-53327d80-ccef-11eb-8bd3-7f7e0f77e1ff.png)[](https://github.com/MuhammadSufyanMalik) • 
I am getting these errors while following your code.

image

@[MuhammadSufyanMalik](https://github.com/MuhammadSufyanMalik) MuhammadSufyanMalik changed the title FirebaseMessaging.onBackgroundMessage() FirebaseMessaging.onBackgroundMessage() .createNotificationChannel, FirebaseMessaging.instance(Not able to declare these all.) [on 14 Jun 2021](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#event-4883465504)[](https://github.com/karankharode)
@[karankharode](https://github.com/karankharode)
Owner
karankharode commented [on 15 Jun 2021](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#issuecomment-861204848)[](https://github.com/karankharode)
This is an Invalid Issue...No such error occurs with the same Dependency version and the same implementation.
Please share the details of your code and implementation to search for any error with implementation.
I am closing this issue for the same.
Thanks and please contact for more assistance.

@[karankharode](https://github.com/karankharode) karankharode closed this [on 15 Jun 2021](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#event-4889422680)[](https://github.com/MuhammadSufyanMalik)
@[MuhammadSufyanMalik](https://github.com/MuhammadSufyanMalik)
Author
MuhammadSufyanMalik commented [on 15 Jun 2021](https://github.com/karankharode/Flutter-2.0-Firebase-Push-Notifications/issues/1#issuecomment-861495969)[](https://github.com/divyadave1205)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
This is an Invalid Issue...No such error occurs with the same Dependency version and the same implementation.
Please share the details of your code and implementation to search for any error with implementation.
I am closing this issue for the same.
Thanks and please contact for more assistance.

I came to know my issue it was my firebase version issue.
Thanks
we will be waiting for IOS notification. :)

@divyadave1205

 
 
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines)[](https://github.com/MuhammadSufyanMalik)[](https://github.com/karankharode)[](https://github.com/).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re not receiving notifications from this thread.
2 participants
@MuhammadSufyanMalik
@karankharode
© 2022 GitHub, Inc.
[Terms](https://docs.github.com/en/github/site-policy/github-terms-of-service)
[Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
[Contact GitHub](https://support.github.com/?tags=dotcom-footer)
[Pricing](https://github.com/pricing)
[API](https://docs.github.com/)
[Training](https://services.github.com/)
[Blog](https://github.blog/)
[About](https://github.com/about)
