### ISSUE TITLE
firebase_messaging-9.1

### ISSUE THREAD

**Issue by JayChitaniya** [karankharode/Flutter-2.0-Firebase-Push-Notifications#2]
i got this error every time when i try to run app
  **firebase_messaging 9.1.4**
/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:20: error: cannot find symbol
**import com.google.firebase.iid.FirebaseInstanceId;**
                              ^
  symbol:   class FirebaseInstanceId
  location: package com.google.firebase.iid

i am using android studio
thanks in advance.....
![error_2021-06-29_12-18-52](https://user-images.githubusercontent.com/86648166/123750520-4fe4e780-d8d4-11eb-881c-e388de97aa00.png)

**Comment by santosh565** [comment]
any solutions @JayChitaniya ? i'm facing the same issue

**Comment by NishaJain24** [comment]
#  Firstly check your app has google-services.json file of  your code.
      #  Please Invalidate & Restart your app.
      
      For me its worked but I also changed so many dependencies version according to today's updated android studio.
      
      For further details I am providing source code available on github.
      
      Link :  https://github.com/NishaJain24/fcm_flutter_notifications

**Comment by Ashutosh980** [comment]
just upgrade messaging to 9.1.4 to 10.0.0

**Comment by NishaJain24** [comment]
Where?

**Comment by Ashutosh980** [comment]
Pubspec.yaml
